services:
  xrpl-backend:
    build: ./backend
    ports:
      - '${BE_PORT}:3001'
    environment: ['PG_CONN=${PG_CONN}', 'XRPL_CLIENT=${XRPL_CLIENT}']
    depends_on:
      db:
        condition: service_healthy
    command: ['node', 'main.js']
    networks:
      - default

  db:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  xrpl-frontend:
    build: ./frontend
    ports:
      - '${FE_PORT}:3000'
    depends_on:
      - xrpl-backend
    networks:
      - default
volumes:
  database:

networks:
  default:
